### ISSUE TITLE
v0.4.0 gcppubsub.yaml release artifact empty

### ISSUE THREAD

**Issue by brosner** [knative/eventing-sources#213]
## Expected Behavior
The release artifact, `gcppubsub.yaml`, for the v0.4.0 release should contain the YAML manifest to run the GCP PubSub controller

## Actual Behavior
The release artifact contains only a comment.

**Comment by n3wscott** [comment]
I think @evankanderson has corrected this.

**Comment by mchmarny** [comment]
Still empty

**Comment by grantr** [comment]
`message-dumper.yaml` is also empty. I'm looking into this.

**Comment by evankanderson** [comment]
It looks like the files are not _empty_, which would produce an error, but don't contain anything useful:

```yaml

---
# gcppubsub.yaml
```

I'm out for the next couple days, but the first step would be to check whether nightly is impacted the same way.

**Comment by grantr** [comment]
It appears the images for message dumper and gcppubsub source were never published.

The issue is in the release script as currently configured:

https://github.com/knative/eventing-sources/blob/850fc5b7f87c94d2162dfad748356f6a158fa2df/hack/release.sh#L21-L33

When a release file has the same name as a component, the publish for that release file fails before uploading any images or yaml artifacts, but _this does not fail the release_.

```sh
Assembling Knative Eventing Sources - message-dumper.yaml
cat: message-dumper.yaml: input file is output file
Assembling Knative Eventing Sources - gcppubsub.yaml
cat: gcppubsub.yaml: input file is output file
Assembling Knative Eventing Sources - release.yaml
New release built successfully
```

I've got a fix for the duplicate artifact names, but I'm not sure how to make the release fail if any components fail. I tried adding `set -e` but that didn't work.

**Comment by evankanderson** [comment]
My release process was to copy the Prow nightly outputs to the release; this revealed silent release script failures in `knative/eventing` with empty files (`hub release` fails on empty files), but since these files aren't quite empty, I copied the useless files to the release without realizing it.

**Comment by grantr** [comment]
If we can get Prow to repeat the release with the same hashes, we can correct 0.4.0 by uploading just the missed images and yamls. If Prow doesn't generate the same hashes as before, I recommend creating a new release 0.4.1.

**Comment by grantr** [comment]
[v0.4.1](https://github.com/knative/eventing-sources/releases/tag/v0.4.1) has been released to correct this.
