### ISSUE TITLE
default source file confusion

### ISSUE THREAD

**Issue by matzew** [knative/eventing-sources#89]
More a question...

why does the `default-gcppubsub` file contain four sources?

* ContainerSource
* GcpPubSubSource
* GitHubSource
* KubernetesEventSource

I think I'd expect it is just `GcpPubSubSource` that's in there.

The `default` on the other hand, contains: 
* ContainerSource
* GitHubSource
* KubernetesEventSource

Not sure I agree the `GitHubSource` is in there - seems a bit specialised, so would have expected only `ContainerSource` and `KubernetesEventSource` in that `default` file.

Would it make sense to have only the PubSub source in `pubsub.yaml` file? Similar for Github?

**Comment by bbrowning** [comment]
I agree it is a bit confusing, and we should decide when a Source gets added to `default.yaml`, gets its own `default-*.yaml`, or should exist as a completely separate controller with separate release files.

**Comment by matzew** [comment]
Not sure I like the `default-xyz` file name for each source. I think the default in there is confusion too.

**Comment by n3wscott** [comment]
We did this because pubsub crashloops if it is not provided the correct creds.

**Comment by evankanderson** [comment]
A few additional details:

Right now, all the controllers are built into the same binary (`github.com/knative/eventing-sources/cmd/manager`), and it seems like only the pubsub source is flagged on/off via environment variables.

A few other interesting items from the combined yaml:

The `manager-role` YAML seems to duplicate permissions for the following:
* apps/deployment
* sources.eventing.knative.dev/containersources
* serving.knative.dev/services

It also has create/update/patch/delete permissions on k8s events, which is probably not needed.

An interesting question is whether we want to try to bundle controllers or separate them:

**Pros of bundling**:
- Fewer resources (easier to fit on minikube) and possibly fewer yaml files.
- Users don't need to solve dependency trees (e.g. `kuberneteseventsource` is implemented via `containersource`).

**Cons of bundling**:
- RBAC applies to the whole controller.
- Installation becomes somewhat more complicated.
- Higher resource requirements.


I think @grantr and myself are anti-bundling, so we may try to break these apart for 0.2.1. In the case of `kuberneteseventsource`, we may end up including all the YAML for the `containersource` in the `kuberneteseventsource` release, and documenting that you get a twofer. Since kubernetes is declarative, it should be fine to re-declare the `containersource` twice if you already have `containersource` installed, and this saves users from needing to solve or understand the dependency graph to get started.

**Comment by n3wscott** [comment]
I think we fixed this moving away from kustomize.

/close
